Codeit-FE08-Part4-Team7/wedo

- hooks/useToggle.ts
- useToggle 커스텀 훅 구현
- useToggle은 boolean값을 true이면 false, false이면 true로 바꿔줘야하는 state를 편하게 사용할 수 있게 만든 커스텀 훅입니다.
- 현업에서도 많이 사용하는 hook이라고 말씀해주셔서 항상 프로젝트때 마다 만들어서 사용중입니다.
- 기존까지는 setState는 따로 return해주진 않았는데 진짜 가끔 필요할때도 있어서 한번 return에 넣었습니다. 평소에는 setState까지 가져다 쓸 필요는 없습니다!
- 혹시 궁금한 것 있으시면 질문해주세요~
- Closes #31
> Feat: useToggle 커스텀 훅 구현

- .vscode/settings.json
- app/(pages)/(자유게시판)/addboard/page.tsx
- app/(pages)/(자유게시판)/board/[id]/page.tsx
- app/(pages)/(자유게시판)/boards/page.tsx
- app/(pages)/page.tsx
- components/@common/Input.tsx
- components/@common/Textarea.tsx
- styles/globals.css
- 공용 컴포넌트 Input 추가
- 공용 컴포넌트 Textarea 추가
- cva 인텔리센스 동작용 코드 추가
- cva 내부에서 Tailwind css 인텔리센스 미동작
- 동작용 코드 추가
- 페이지 추가
- boards
- board
- addboard
- (자유게시판) 그룹 안에 추가
- scrollbar 스타일 변경
- 작업용 페이지 링크 추가/제거
- 렌딩 -> 자유게시판 링크 제거
- 자유게시판 -> 게시물 상세, 게시물 등록 링크 추가
- 
- close #24
> Feat: 공용 컴포넌트 Input/Textarea, cva 인텔리센스, 페이지 파일, scrollbar style 추가

- components/@common/modal/Dialog.tsx
- components/@common/modal/Sheet.tsx
- 모달 디자인을 일부 수정했습니다.
- Issue에서 설명된 내용과 같은 변경사항입니다! (Description font 색상 + 모바일 gap 추가)
- 혹시 modal 사용하시는 분들은 변경사항 꼭 확인하고 테스트 하시기바랍니다!
- Closes #50
> Design: 모달 디자인 수정

- components/@common/container/Container.tsx
- 페이지 마다 배경색이 다른 경우가 있어  Container 컴포넌트에 background props를 추가하였습니다..
- header의 height 값 만큼 padding top 추가하였습니다.
- 최소 height 값도 추가하였습니다.
```javascript
const backgroundColors = {
white: "inverse",
lightBeige: "primary-light",
};
white와 lightBeige 색을 쓸 수 있습니다.
```
**사용예시**
```javascript
<Container background="white"> Content </Container> // 흰색으로 지정
```
- Closes #55
> Feat: Container 컴포넌트에 background props를 추가한다

- app/(pages)/layout.tsx
- components/@common/container/Container.tsx
- 템플릿 리터럴을 사용해서 동적으로 클래스명을 생성할 경우 Tailwind는 빌드 시점에 정적인 클래스 명만 처리를 하기 때문에 조건부로 클래스네임을 받아오도록 수정하였습니다.
- app/layout에 있는 pt값 제거, div -> Fragment, main태그로 변경하였습니다
- 리뷰가 필요한 부분에 대해서 작성해주세요
- Closes #58
> Refactor: Container 컴포넌트에 백그라운드 클래스 명 지정 방식을 수정한다.

- components/@common/modal/Modal.tsx
- 이슈 #66 의 내용을 해결하였습니다
1. onOpenChange prop을 추가하여 trigger에 boolean값을 사용할 때에도 sync를 맞춰줄 수 있게 되었습니다. 외부에서 관리되는 isOpen state의 toggle 함수를 전달해주면 됩니다. 이외에도 모달이 열리거나 닫힐때 실행해주고 싶은 동작도 같이 전달할 수 있습니다.
```js
...
const [isEditModalOpen, toggleIsEditModalOpen] = useToggle(false);
...
<Modal
trigger={isEditModalOpen} // trigger에 boolean state 사용
type="modal"
onOpenChange={toggleIsEditModalOpen} // trigger에 boolean state 사용시 해당 toggleState 함수를 전달
footer={
<Button className="flex-1" onClick={handleTeamEditButtonClick}>
수정 하기
</Button>
}
>
<Input
placeholder="팀 이름을 작성해주세요."
onChange={handleTeamNameInputChange}
value={teamNameInputValue}
/>
</Modal>
...
```
2. title과 description에 react element도 받을 수 있도록 수정하였습니다. <br/>태그를 이용해 줄바꿈도 가능합니다.
3. modal의 디자인에 padding이 다른 경우를 대비해 contentClassName prop으로 className을 …
> Fix/Refactor: 모달 버그 및 기능 수정 #66

- apis/action.ts
- apis/auth.ts
- app/(pages)/signup/page.tsx
- components/auth/login/LoginForm.tsx
- components/auth/signup/SignUpForm.tsx
- dtos/AuthDtos.ts
- package-lock.json
- package.json
- 회원가입 페이지 구현 완료
- 디자인은 로그인 페이지랑 비슷해서 자세히 안봐도 될 것 같아요
- 회원가입이 잘되는지만 보시고, 이미 가입된 경우 발생하는 에러가 잘 표시되는지 확인하시면 될 것 같아요
- Closes #79
> Feat: 회원가입 페이지 구현

- package-lock.json
- package.json
- dayjs 라이브러리 설치하였습니다
- 라이브러리만 설치한 커밋입니다~
- 기타 참고, 요구 사항을 작성해주세요
- 이미지 첨부 (선택)
- 관련된 이슈가 있다면, PR 작성 맨 아래에서 이슈 연결 키워드도 작성해 주세요.
> Chore: dayjs 라이브러리를 설치한다

- app/(pages)/(자유게시판)/board/[id]/page.tsx
- app/(pages)/(자유게시판)/boards/page.tsx
- 중간 정검용 업로드
- 모든 기능이 구현되지 않았습니다.
- 
- close #88 #89
> Feat: 자유게시판, 게시물 상세 페이지 임시 구현

- app/(pages)/login/page.tsx
- build 시 에러가 발생하여 OAUTH_PARAMS에 export 제거
> Fix: OAUTH_PARAMS export 제거

- apis/auth.ts
- apis/fetchExtended.ts
- app/api/auth/refresh-token/route.ts
- middleware.ts
- refreshToken 문제였던 걸 수정함 (그러나 왜 되는지 모르겠음)
- 이 PR을 반영한 뒤 이전과 같은 에러가 뜨는지 확인만 해주시면 됩니다.
- accessToken의 주기가 1시간으로 되어 있어서, 이 점 참고하시면 좋을 것 같아요
- Closes #114
> Fix: refreshToken 에러수정 (테스트는 완벽하게 해보지 못함)

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-main.yml
- build.sh
- dev 및 main 브랜치 빌드 자동화를 위한 github action을 추가합니다.
- 궁금한게 있으시면 말씀해주세요~
- Closes #111
> Chore: dev 및 main 브랜치 빌드 자동화 액션 추가

- routes.ts
- middleware에서 사용하는 routes.ts 파일 최신화
- 빌드 했을 때 잘되는지 확인하시면 됩니다.
> Fix: routes.ts 파일 업로드

- components/team/with_team/TeamReport.tsx
- components/team/with_team/TodoReportChartSide.tsx
- components/team/with_team/WithTeam.tsx
- 팀 페이지 중 리포트 부분을 구현하였습니다.
- 리포트는 해당 팀을 만든 admin일 때만 보여집니다.
- 우선은 보여지기만 하는 부분이라 UI 구현을 완료했습니다! 혹시 궁금하신게 있으시면  comment로 남겨주세요~
- Closes #84
> Feat: 팀 페이지 기능 구현 (리포트)

- package-lock.json
- package.json
- react-visually-hidden를 설치 했습니다
- shadcn sheet 사용 시 title과 description을 사용하지 않을 때 필요하다 해서 설치했습니다
- 리뷰가 필요한 부분에 대해서 작성해주세요
- 기타 참고, 요구 사항을 작성해주세요
- 이미지 첨부 (선택)
- 관련된 이슈가 있다면, PR 작성 맨 아래에서 이슈 연결 키워드도 작성해 주세요.
> Chore: react-visually-hidden 설치

- apis/user.ts
- app/(pages)/history/page.tsx
- components/tasks/taskList/DoneTask.tsx
- dtos/TaskDtos.ts
- 마이 히스토리 페이지를 구현하였습니다.
- 날짜 별로 필터링 되어 정렬 됩니다
- 마이 히스토리 api 및 type 추가하였습니다.
- 궁금하신점 써주세요~
- Closes #86
> Feat: 마이히스토리 페이지를 구현 한다

- components/@common/modal/NewModal.tsx
- button 내부에 button이 추가로 있어서 hydration error가 발생하던 것을 수정하였습니다!
- Modal 사용하시는 분들도 나중에 ModalClose나 ModalTrigger 같은 경우에는 button이기 때문에 내부에 button을 사용하는 경우 asChild 꼭 사용하시길 권장합니다!
- Closes #149
> Fix: modal hydration error 수정

- components/@common/dropdown/NavigationMenu.tsx
- components/@common/dropdown/UserDropDown.tsx
- components/auth/InputField.tsx
- components/auth/login/LoginForm.tsx
- components/auth/login/ResetPasswordEmailModal.tsx
- components/auth/mypage/PasswordEditForm.tsx
- components/auth/mypage/ProfileEditInput.tsx
- components/auth/reset-password/ResetPasswordForm.tsx
- components/auth/signup/SignUpForm.tsx
- 2차 QA에 나온 버그 일부분 제외하고 수정 완료
- 수정 사항에 대한 자세한 내용은 #140 을 참고해주세요
- #140
> Fix: 2차 QA

- components/team/with_team/MemberCard.tsx
- components/team/with_team/TeamDelModal.tsx
- components/team/with_team/TeamEditModal.tsx
- components/team/with_team/TeamInviteModalButton.tsx
- components/team/with_team/TeamTaskListAddModalButton.tsx
- components/team/with_team/TeamTaskListDelModal.tsx
- components/team/with_team/TeamTaskListEditModal.tsx
- components/team/with_team/TeamTitle.tsx
- 모달 기능 오류 및 디자인 수정을 진행하면서 리팩토링을 진행하였습니다.
- 관련된 기능 오류 및 디자인 문제는 이슈 #98 을 참고해주세요!
- react-hook-form, 새로 만들어진 modal 그리고 공통 image input을 이용해서 리팩토링을 진행하였습니다.
- pull 당기셔서 직접 확인해보시면 좋을 것 같아요!
- Closes #98
> Fix/Refactor: 모달 버그 수정 및 리팩토링

- app/(pages)/reset-password/@auth/default.tsx
- app/(pages)/reset-password/@auth/page.tsx
- app/(pages)/reset-password/layout.tsx
- components/auth/InputField.tsx
- components/auth/login/LoginForm.tsx
- components/auth/mypage/PasswordEditForm.tsx
- components/auth/mypage/ProfileEditInput.tsx
- components/layout/AuthHeader.tsx
- lib/cookie.ts
- #151 내용 수정
- 비밀번호 재설정 모달과 reset-password 로그인 상태에 따른 변경점 살펴주시면 됩니다.
- Closes #151
> Fix: 2차 QA 추가 해결

- app/(pages)/history/page.tsx
- 완료를 한 날짜가 아닌 목록 등록 날짜 기준으로 정렬 되도록 수정
- 중복으로 완료된 목록이 뜨는 현상 수정
- 리뷰가 필요한 부분에 대해서 작성해주세요
-  Closes #135
> Fix: 히스토리 페이지 수정 사항

- components/@common/modal/NewModal.tsx
- components/team/with_team/MemberCard.tsx
- components/team/with_team/TeamDelModal.tsx
- components/team/with_team/TeamTaskListDelModal.tsx
- NewModal을 button으로 사용함에 따라 나타나는 문제를 해결하였습니다.
- 이에 따라 footer를 사용하는 다른 modal을 수정하였습니다.
- 새로운 모달 관련 PR의 사용법도 수정합니다! #147 
- Closes: #153
> Fix: NewModal의 ModalFooter 구조 변경

- components/team/with_team/TeamTaskListEditModal.tsx
- components/team/with_team/TodoReportChartSide.tsx
- 팀 페이지 UI 디자인을 일부 수정하였습니다.
- 디자인 수정이라 큰 문제는 없습니다!
- Closes: #156
> Fix/Design: 팀 페이지 UI 디자인 수정

- apis/task.ts
- 할 일 생성에 날짜 부분에서 build시 타입 에러가 나는 것 수정하였습니다
해당부분
수정완료
- 리뷰가 필요한 부분에 대해서 작성해주세요
-
> Fix: type 오류 수정

- components/tasks/taskList/TaskCard.tsx
- components/tasks/tasksMenu/TasksMenu.tsx
- 할 일 리스트들이 일정 크기 이상 줄어들 때 줄 바꿈 되도록 수정
- pc일때는 목록들이 줄 바꿈 되도록 수정
- 날짜 변경 후 목록 이동 할 때 선택 날짜의 목록이 안보이는 현상 수정
- 버그있으면 알려주세용
- #108 #131
> Fix: 할 일 목록 페이지 수정

- apis/action.ts
- app/(pages)/layout.tsx
- app/(pages)/loading.tsx
- app/layout.tsx
- components/@common/Loading.tsx
- components/@common/button/Submit.tsx
- components/@common/dropdown/UserDropDown.tsx
- components/auth/login/ResetPasswordEmailModal.tsx
- components/layout/AuthHeader.tsx
- components/layout/HeaderLayout.tsx
- components/ui/spinner.tsx
- loading.tsx 파일을 추가하여 페이지 이동 시에 로딩이 출력되도록 구현(UI는 아직 고려 안함)
- 그 외 HeaderLayout 배치 수정하고, signOut 로직 변경
- loading.tsx 파일을 적용했지만 모든 페이지에서 잘 적용되는건 아니였습니다. 이유를 아직 모르겠어서, 안되는 특정 페이지가 있으면 알려주시면 감사합니다.
- HeaderLayout을 옮기며 signOut 로직을 조금 수정했습니다. 로직은 중요하지 않고, 로그아웃을 클릭했을 때 "로그아웃 중..."이라고 보이게 했는데, 더 좋은 디자인 있으면 추천해주세요
- #163
> Feat: loading.tsx 추가

- app/(pages)/error.tsx
- error.tsx를 사용해 UX향상
- 에러메세지와 새로고침 버튼을 포함한 페이지를 띄워 유저가 필요한 조치를 할 수 있도록 구현
- 의도적으로 에러를 발생시켜보고, error 페이지를 확인해주시면 감사합니다.
- #167
> Feat: error.tsx 추가

- apis/article.ts
- app/(pages)/(자유게시판)/board/[id]/CommentForm.tsx
- app/(pages)/(자유게시판)/board/[id]/CommentList.tsx
- app/(pages)/(자유게시판)/board/[id]/PatchAndDelete.tsx
- app/(pages)/(자유게시판)/board/[id]/PatchArticle.tsx
- app/(pages)/(자유게시판)/board/[id]/action.ts
- app/(pages)/(자유게시판)/board/[id]/page.tsx
- app/(pages)/(자유게시판)/boards/action.ts
- app/(pages)/(자유게시판)/boards/page.tsx
- app/(pages)/(자유게시판)/boards/section/Article.tsx
- app/(pages)/(자유게시판)/boards/section/BestArticle.tsx
- components/board/ImagePreviewInput.tsx
- components/content/BestBadge.tsx
- components/layout/groups/GroupsResponsive.tsx
- components/layout/groups/boardsLink.tsx
- dtos/Article.d.ts
- styles/globals.css
- 베스트 배지 컴포넌트 내부 요소 위치 조정
- PatchArticle -> CommentList 컴포넌트 이름 변경
- 코드 분할
- CommentForm, CommentList 컴포넌트
- Fix: ImagePreviewInput 컴포넌트 기능 확장
- 이미지 변경할 수 있게 코드 추가
- Fix: 폼 제출 후 인풋 초기화
- 
- 게시글 검색 기능과 URL 연동 자잘한 수정 중
- close
> Feat/Fix: 게시판 페이지 기능 확장, 게시글 페이지 수정

- action/content.ts
> Fix: 타입 에러 수정
